Included Portainer for Maintaining

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,10 @@
 name: CI/CD Pipeline
+
 on:
   push:
     branches:
       - main
+
 jobs:
   build_and_push:
     runs-on: ubuntu-latest
@@ -22,19 +24,24 @@ jobs:
     - name: Run tests
       run: |
         pytest
+
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
+
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
+
     - name: Build Docker image
       run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .
+
     - name: Push Docker image
       run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
+
   deploy:
     name: Deploy to EC2
     runs-on: ubuntu-latest
@@ -43,11 +50,10 @@ jobs:
     - name: Set up SSH
       env:
         PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        HOSTNAME: ${{ secrets.SSH_HOST }}
-        USER_NAME: ${{ secrets.USER_NAME }}
       run: |
         echo "$PRIVATE_KEY" > private_key
         chmod 600 private_key
+
     - name: Deploy Docker container to EC2
       env:
         HOSTNAME: ${{ secrets.SSH_HOST }}
@@ -68,9 +74,18 @@ jobs:
           
           # Pull the latest Docker image
           echo "Pulling latest image..."
-          sudo docker pull $DOCKER_USERNAME/my-flask-app:latest
+          docker pull $DOCKER_USERNAME/my-flask-app:latest
           
           # Run the new Docker container
           echo "Starting new container..."
-          sudo docker run -d --name my-flask-app -p 5000:5000 $DOCKER_USERNAME/my-flask-app:latest || echo "Failed to start the new container."
+          docker run -d --name my-flask-app -p 5000:5000 $DOCKER_USERNAME/my-flask-app:latest || echo "Failed to start the new container."
+
+          # Ensure Portainer is running
+          if ! docker ps --format '{{.Names}}' | grep -q '^portainer$'; then
+            echo "Starting Portainer..."
+            docker volume create portainer_data
+            docker run -d -p 9000:9000 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
+          else
+            echo "Portainer is already running."
+          fi
         EOF
